### ISSUE TITLE
Add Quay context

### ISSUE THREAD

**Issue by JAORMX** [lammaskoira/bark#24]
A new context provider dedicated for querying information from Quay would be very useful. This would enable us to get information about container image tags and even their vulnerabilities if proper integration with Clair would be enabled.

Configuration could look as follows:

```yaml
context:
  provider: quay
  quay:
    org: lammaskoira
```

The provider would query the Quay API for images in the organization and persist that in an `input` for the policy engine to consume.
