### ISSUE TITLE
Add Kubernetes context

### ISSUE THREAD

**Issue by JAORMX** [lammaskoira/bark#25]
The idea would be to have a context provider that retrieves information from a Kubernetes cluster. Configuration could look as follows:

```yaml
context:
  provider: kubernetes
  kubernetes:
    resourcePaths:
      - v1/pods
      - v1/configmaps
      - apps/v1/deployments
```

The context provider would then query the cluster whose context it has available and insert the resources into an input that the policy engine can consume.

The path format is useful since it allows for retrieving resources in a namespaced manner, or globally.
